repos:
  - repo: local
    hooks:
      - id: docs_readme
        name: docs_readme
        entry: parse_docs -p docs -e .md -s 01_brief_description 02_introduction 03_compute_requirements 04_install_and_run 05_related_protocols 06_input_example 06_input_parameters 07_outputs 08_pipeline_overview 09_troubleshooting 10_FAQ 11_other -ot README.md -od output_definition.json -ns nextflow_schema.json
        language: python
        always_run: true
        pass_filenames: false
        additional_dependencies:
          - epi2melabs==0.0.57
      - id: build_models
        name: build_models
        entry: datamodel-codegen --strict-nullable --base-class workflow_glue.results_schema_helpers.BaseModel --use-subclass-enum --use-schema-description --disable-timestamp --input results_schema.yml --input-file-type openapi --output bin/workflow_glue/results_schema.py
        language: python
        files: 'results_schema.yml'
        pass_filenames: false
        additional_dependencies:
          - datamodel-code-generator
  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        pass_filenames: false
        additional_dependencies:
          - flake8-rst-docstrings
          - flake8-docstrings
          - flake8-import-order
          - flake8-forbid-visual-indent
          - pep8-naming
          - flake8-no-types
          - flake8-builtins
          - flake8-absolute-import
          - flake8-print
        args: [
            "bin",
            "--import-order-style=google",
            "--statistics",
            "--max-line-length=88",
            "--extend-exclude=bin/workflow_glue/results_schema.py",
        ]
